services:
  nginx:
    image: nginx:alpine
    container_name: videoeditor-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount certs read-only
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: videoeditor-frontend
    # ports:
    #   - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: videoeditor-backend
    # ports:
    #   - "8000:8000"
    volumes:
      - ./out:/app/out
    # Memory configuration for video rendering
    mem_limit: 2g
    memswap_limit: 2g
    shm_size: 1g

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: videoeditor-fastapi
